spring:
  datasource:
    url: jdbc:mysql://192.168.45.44:3306/kioskdb
    username: kiosk_user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
